---
version: '3'
services:
  bionic:
    container_name: bionic
    image: naftulikay/bionic-vm:latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    stop_grace_period: 1s

  centos7:
    container_name: centos7
    image: naftulikay/centos7-vm:latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    stop_grace_period: 1s

  juno:
    container_name: juno
    image: naftulikay/juno-vm:latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    stop_grace_period: 1s

  loki:
    container_name: loki
    image: naftulikay/loki-vm:latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    stop_grace_period: 1s

  trusty:
    container_name: trusty
    image: naftulikay/trusty-vm:latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    stop_grace_period: 1s

  xenial:
    container_name: xenial
    image: naftulikay/xenial-vm:latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    stop_grace_period: 1s
